export enum Pages {
	MAIN = 'main',
	LOGIN = 'login',
	SIGNUP = 'signup',
	PINCODE_LOGIN = 'pincodeLogin',
	MAIN_MENU = 'mainMenu',
	HOME_PAGE = 'homePage',
	ACCOUNT_EDITOR = 'accountEditor',
	ACCOUNT_EDITOR2 = 'accountEditor2',
	ACCOUNT_EDITOR3 = 'accountEditor3',
	ASSET_EDITOR = 'assetEditor',
	ASSET_EDITOR2 = 'assetEditor2',
	ASSET_EDITOR3 = 'assetEditor3',
	GROUP_EDITOR = 'groupEditor',
	GROUP_EDITOR2 = 'groupEditor2',
	GROUP_EDITOR3 = 'groupEditor3',
}
