export const accountEmojis = [
	{
		category: 'objects',
		keywords: [
			'credit card',
			'credit cards',
			'debit card',
			'debit cards',
			'money',
			'sales',
			'dollar',
			'bill',
			'payment',
			'shopping',
		],
		name: 'credit card',
		order: 132,
		unified: '1F4B3',
		emoji: '💳',
	},
	{
		category: 'objects',
		keywords: [
			'yen',
			'cash',
			'money',
			'currency',
			'yen banknote',
			'sales',
			'japanese',
			'dollar',
			'banknote with yen sign',
		],
		name: 'banknote with yen sign',
		order: 127,
		unified: '1F4B4',
		emoji: '💴',
	},
	{
		category: 'objects',
		keywords: [
			'dollar',
			'cash',
			'money',
			'dollars',
			'dollar banknote',
			'sales',
			'bill',
			'currency',
			'banknote with dollar sign',
		],
		name: 'banknote with dollar sign',
		order: 128,
		unified: '1F4B5',
		emoji: '💵',
	},
	{
		category: 'objects',
		keywords: [
			'euro',
			'euros',
			'euro banknotes',
			'money',
			'cash',
			'euro banknote',
			'sales',
			'dollar',
			'currency',
			'banknote with euro sign',
		],
		name: 'banknote with euro sign',
		order: 129,
		unified: '1F4B6',
		emoji: '💶',
	},
	{
		category: 'objects',
		keywords: [
			'money',
			'cash',
			'sterling pounds',
			'british pounds',
			'quid',
			'pound banknote',
			'british',
			'sterling',
			'sales',
			'bills',
			'uk',
			'england',
			'currency',
			'pound',
			'banknote with pound sign',
		],
		name: 'banknote with pound sign',
		order: 130,
		unified: '1F4B7',
		emoji: '💷',
	},
	{
		category: 'objects',
		keywords: [
			'cash',
			'money',
			'money with wings',
			'dollar',
			'bills',
			'payment',
			'sale',
		],
		name: 'money with wings',
		order: 131,
		unified: '1F4B8',
		emoji: '💸',
	},
	{
		category: 'objects',
		keywords: [
			'briefcase',
			'portfolio',
			'bag',
			'briefcases',
			'portfolios',
			'bags',
			'business',
			'documents',
			'work',
			'law',
			'legal',
			'job',
			'career',
		],
		name: 'briefcase',
		order: 155,
		unified: '1F4BC',
		emoji: '💼',
	},
	{
		category: 'objects',
		keywords: ['file folder', 'documents', 'business', 'office'],
		name: 'file folder',
		order: 156,
		unified: '1F4C1',
		emoji: '📁',
	},
	{
		category: 'objects',
		keywords: [
			'chart increasing',
			'graph',
			'presentation',
			'stats',
			'recovery',
			'business',
			'economics',
			'money',
			'sales',
			'good',
			'success',
			'chart with upwards trend',
		],
		name: 'chart with upwards trend',
		order: 164,
		unified: '1F4C8',
		emoji: '📈',
	},
	{
		category: 'objects',
		keywords: ['bar chart', 'bar charts', 'graph', 'presentation', 'stats'],
		name: 'bar chart',
		order: 166,
		unified: '1F4CA',
		emoji: '📊',
	},
	{
		category: 'objects',
		keywords: [
			'package',
			'box',
			'shipment',
			'delivery',
			'packages',
			'boxes',
			'shipments',
			'deliveries',
			'mail',
			'gift',
			'cardboard',
			'moving',
		],
		name: 'package',
		order: 141,
		unified: '1F4E6',
		emoji: '📦',
	},
	{
		category: 'objects',
		keywords: ['receipt', 'accounting', 'expenses'],
		name: 'receipt',
		order: 133,
		unified: '1F9FE',
		emoji: '🧾',
	},
]
